- e2e-tests-v2/src/checkout.payment.test.js
- e2e-tests-v2/src/utils/helpers.js
- Update XPATHS
- Add 3ds2 verification steps
> Update Checkout v2 end-to-end tests with new XPaths

- api-tests/checkout-tests/checkout-api-dev.tests.json
- api-tests/dev.envs.json
Added test into DEV api-test for execute DELETE transaction api.
> CHK-1272-added-delete-api-test

- .devops/code-review-pipelines.yml
- api-tests/cart-tests/cart-api-dev.tests.json
- api-tests/cart-tests/cart-api-uat.tests.json
- api-tests/checkout-tests/checkout-api-dev.tests.json
- api-tests/checkout-tests/checkout-api-uat.tests.json
- api-tests/dev.envs.json
- api-tests/uat.envs.json
> [CHK-1352] feat(carts): split carts tests into DEV/UAT

- api-tests/uat.envs.json
- api-tests/uat.payment-methods.blue.envs.json
- api-tests/uat.payment-requests.blue.envs.json
- api-tests/uat.transactions.blue.envs.json
> fix: psp id for UAT env

- api-tests/cart-tests/cart-api-dev.tests.json
- api-tests/cart-tests/cart-api-uat.tests.json
dependOn: https://github.com/pagopa/pagopa-checkout-tests/pull/54
Added valid notice code generation using a pre-script for fix UAT test problems
The change was made to resolve problems in UAT on the cart tests.
See Api _Tests_Carts stage
- DEV: https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=92137&view=logs&s=8c133786-9d1a-5e48-a9a9-2145ae3c6120
- UAT: https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=92132&view=logs&j=c3f6a3f6-9265-5a60-0d2b-4c1e34729fdd&t=c3f6a3f6-9265-5a60-0d2b-4c1e34729fdd
The tests were carried out in local
> fix-cart-test-for-uat

- api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json
Add recaptcha token to post transaction
> Add recaptcha response to post transaction

- api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json
Added x-transaction-id into POST payment-method/:id/fees request for log correlation
The change was made to allow validation of the request via the transactionId.
> feat: added x-transaction-id into header for POST fee

- api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json
Fix api test for checkout with authToken into calculate fee request.
Renamed header from **x-transaction-id** to **x-transaction-id-from-client**
> Feat: added auth token into api test for POST /fees

- api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json
Update api test to involve allCCP flag
> [CHK-1634] fix test for allCCP flag adding

- api-tests/cart-tests/cart-api-dev.tests.json
- api-tests/cart-tests/cart-api-uat.tests.json
- api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json
Add api test with mail in upper case.
Tests were add for:
- payment-requests (cart creation)
- transactions-service (new transaction)
Those tests will cover cases for which mail is written with uppercase characters
> feat(api-test): add test for mail case insensitive

- api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json
- api-tests/dev.envs.json
- api-tests/uat.envs.json
- api-tests/uat.payment-methods.blue.envs.json
- api-tests/uat.payment-requests.blue.envs.json
- api-tests/uat.transactions.blue.envs.json
> fix(test): test for payment method information

- api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json
Fixed payment method name from Carte to CARDS
> fixed(tests) : modified body of expected payment method

- .devops/azure-templates/e2e-tests.yaml
- .devops/code-review-pipelines.yml
- README.md
Add azure template to be used in pipelines to perform e2e Checkout tests
Add azure template to be used in pipelines to perform e2e Checkout tests
Pipeline [execution](https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=122687&view=results)
Azure pipeline execution
> feat(pipeline): [CHK-1873] - create template for e2e test execution

- .devops/code-review-pipelines.yml
- api-tests/checkout-tests/pgs/checkout-for-ecommerce-api.tests.json
- api-tests/uat.envs.json
Fixed UAT collection tests for PGS flow
> fix: uat collection test

- e2e-tests/dev.env
- e2e-tests/src/npg/checkout.npg.integration.test.ts
- e2e-tests/src/npg/helpers.js
Add NPG e2e tests for all supported PSP
Those modification are needed in order to perform E2E tests for all psps
Local yarn test + [pipeline](https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=129820&view=results)
> feat: NPG integration test for all PSP

- e2e-tests/dev.env
- e2e-tests/src/npg/checkout.npg.integration.test.ts
Change NPG Nexi test card
Enable NPG E2E test
Those modification are required to test NPG integration using Nexi psp
local tests + pipeline
> fix: [CHK-2122] - enable NPG nexi e2e test

- api-tests/uat.envs.json
> fix: fee for uat tests

- api-tests/checkout-tests/npg/checkout-for-ecommerce-api.tests.json
Add `methodManagement` field id to the field id list to check versus payment methods data retrieved
Depends on https://github.com/pagopa/pagopa-ecommerce-payment-methods-service/pull/147
> [CHK-2329] feat(payment-methods): add field id to payment methods fields list to check

- api-tests/checkout-tests/npg/checkout-for-ecommerce-api.tests.json
Saved correlationId into env.
Added correlationId into POST v2/transanctions body
> [CHK-2467] fix: save correlationId into env and used into POST transaction

- api-tests/checkout-tests/npg/checkout-for-ecommerce-api.tests.json
> Fix correlation id

- e2e-tests/dev.env
- e2e-tests/src/npg/checkout.npg.integration.test.ts
Generalize NPG card tests to accept multiple tests for any psp.
This way adding a psp test will result in update dev.env CARD_TEST_DATA json adding the new configuration for psp.
This configuration support also multiple tests for the same psp with different cards configuration
This modification make NPG E2E test configurable by env variable
local test execution
> [CHK-2514] feat: generalize card tests

- .devops/code-review-pipelines.yml
- api-tests/uat.envs.json
- e2e-tests/dev.env
- e2e-tests/uat.env
* update api env for tests in UAT deploy pipelines
> feat(deploy): update api env for tests in UAT deploy pipelines

- e2e-tests/src/npg/checkout.npg.integration.test.ts
Fix checkout e2e tests skipping privacy policy consent click
This modification is needed since privacy policy banner have been removed in place of the new privacy policy popup that can be ignored during e2e tests
> fix: e2e tests privacy policy consent

- e2e-tests/src/npg/checkout.npg.integration.test.ts
- e2e-tests/src/npg/helpers.js
A new banner structure for OT Cookies banner.
> [#CHK-2894] Update test according the new OT banner

- .devops/code-review-pipelines.yml
> fix code review uat e2e pipeline condition

- e2e-tests/src/npg/psp-unavailable-error.npg.integration.test.ts
- set IT as default lang for e2e test psp not found
> fix: CHK-3515 integration test with language

- e2e-tests/src/npg/helpers.js
- Updated the selected payment method from 'card' to 'CP' in the test script
- Ensures the test uses the correct payment method identifier.
> fix: payment method select

- e2e-tests/dev.env
- e2e-tests/src/npg/psp-sorting.npg.integration.test.ts
- e2e-tests/uat.env
Fixed cards to be used in E2E tests
Disabled tests for Nexi and Poste psp since broken in UAT
Fixed psp ordering tests using Paypal instead of Cards to speed up tests and make it more reliable
Fixed cards to be used in E2E tests
Disabled tests for Nexi and Poste psp since broken in UAT
pipeline execution here -> https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=197328&view=results
> fix: cards to be used in tests

- e2e-tests/dev.env
- e2e-tests/src/npg/checkout.npg.integration.test.ts
- e2e-tests/src/npg/helpers.js
- e2e-tests/src/npg/psp-sorting.npg.integration.test.ts
- e2e-tests/uat.env
Fixed previous tests to work with the new psp list page
Added tests for new psp list page
>  [CHK-3870] feat(e2e-tests): update checkout e2e tests

- e2e-tests/src/auth/checkout.spid-auth.integration.test.ts
Remove redundant browser and page initialization into E2E test, using the one initialized with the jest-puppeteers.config file
This duplicated configuration have been discovered analyzing the below issue
```
Failed to launch the browser process!
[2487:2487:0408/161826.050013:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
[0408/161826.062702:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0408/161826.062759:ERROR:file_io_posix.cc(145)] …
```
> fix: remove duplicate jest tests browser configuration

- api-tests/checkout-tests/npg/checkout-for-ecommerce-api.tests.json
- added API test for get transaction outcome on transactions-service
This change was needed to have complete test collection on checkout
- Tested with newman run command on DEV environment
Newman run output:
> feat(api-test): [CHK-4118] add outcome API test to transactions-service collection

- api-tests/auth-service-tests/auth-service-api.oneidentity.tests.json
Removed an assertion from the tests since it wasn't needed and kept giving errors
> fix:[PIDM-519]-Test-Green-UAT
